// Get all trainees constants
export const TRAINEE_LIST_REQUEST = 'TRAINEE_LIST_REQUEST';
export const TRAINEE_LIST_SUCCESS = 'TRAINEE_LIST_SUCCESS';
export const TRAINEE_LIST_FAIL = 'TRAINEE_LIST_FAIL';
export const TRAINEE_LIST_RESET = 'TRAINEE_LIST_RESET';

// Get trainee details constants
export const TRAINEE_DETAILS_REQUEST = 'TRAINEE_DETAILS_REQUEST';
export const TRAINEE_DETAILS_SUCCESS = 'TRAINEE_DETAILS_SUCCESS';
export const TRAINEE_DETAILS_FAIL = 'TRAINEE_DETAILS_FAIL';
export const TRAINEE_DETAILS_RESET = 'TRAINEE_DETAILS_RESET';

// Create trainee constants
export const TRAINEE_CREATE_REQUEST = 'TRAINEE_CREATE_REQUEST';
export const TRAINEE_CREATE_SUCCESS = 'TRAINEE_CREATE_SUCCESS';
export const TRAINEE_CREATE_FAIL = 'TRAINEE_CREATE_FAIL';
export const TRAINEE_CREATE_RESET = 'TRAINEE_CREATE_RESET';

// Update trainee constants
export const TRAINEE_UPDATE_REQUEST = 'TRAINEE_UPDATE_REQUEST';
export const TRAINEE_UPDATE_SUCCESS = 'TRAINEE_UPDATE_SUCCESS';
export const TRAINEE_UPDATE_FAIL = 'TRAINEE_UPDATE_FAIL';
export const TRAINEE_UPDATE_RESET = 'TRAINEE_UPDATE_RESET';

// Delete trainee constants
export const TRAINEE_DELETE_REQUEST = 'TRAINEE_DELETE_REQUEST';
export const TRAINEE_DELETE_SUCCESS = 'TRAINEE_DELETE_SUCCESS';
export const TRAINEE_DELETE_FAIL = 'TRAINEE_DELETE_FAIL';